name: Run Contact Finder

on:
  workflow_dispatch:    # pozwala uruchomić ręcznie
  push:                 # uruchomi się też po każdym pushu do repo
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CX: ${{ secrets.GOOGLE_CX }}
        run: python main.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: contact-finder-results
          path: |
            out/results.json
            out/results.csv
            out/pages
