name: Run Contact Finder

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify inputs (nazwy.txt + main.py)
        run: |
          echo "Repo root: $(pwd)"
          ls -la
          # Sprawdź pliki wejściowe
          if [ ! -f main.py ]; then
            echo "::error::Brak pliku main.py w katalogu głównym repo."
            exit 1
          fi
          if [ ! -f nazwy.txt ]; then
            echo "::error::Brak pliku nazwy.txt w katalogu głównym repo."
            echo "Utwórz nazwy.txt, np.:"
            echo "Przykładowa Spółka Akcyjna ; 0000123456" 
            echo "Inna Spółka z o.o."
            exit 1
          fi
          if [ ! -s nazwy.txt ];
